name: test deployment

# event
on:
  push:
    branches:
      - main

# to-do when events occur
jobs:
  build:
    name: test build & deploy
    # operating systems
    runs-on: ubuntu-latest

    steps:
      # command name
      - name: command#1`
        # command
        run: echo "hello world !"

      - name: command#2
        run: |
          echo "first command"
          echo "second command"

      - name: command#3
        run: |
          echo $GITHUB.SHA
          echo $GITHUB.REPOSITORY
