name: test deployment

# event
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# to-do when events occur
jobs:
  build:
    name: test build & deploy
    runs-on: ubuntu-latest
